# Generated by Django 4.2 on 2023-04-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID нарушителя')),
                ('intruder_fio', models.CharField(max_length=100, verbose_name='ФИО нарушителя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('description', models.TextField(default='Нет описания (Нежелательное поведение)', verbose_name='Описание нарушителя')),
                ('sex', models.CharField(blank=True, max_length=1, verbose_name='Пол (м/ж)')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('country', models.CharField(blank=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, verbose_name='Область')),
                ('area', models.CharField(blank=True, verbose_name='Район')),
                ('locality', models.CharField(blank=True, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, verbose_name='Дом')),
                ('frame', models.CharField(blank=True, verbose_name='Корпус')),
                ('apartment', models.CharField(blank=True, verbose_name='Квартира')),
                ('injured', models.BooleanField(default=False, verbose_name='Потерпевший')),
                ('intruder', models.BooleanField(default=False, verbose_name='Нарушитель')),
                ('witness', models.BooleanField(default=False, verbose_name='Свидетель')),
            ],
            options={
                'verbose_name': 'Лицо',
                'verbose_name_plural': 'Лица',
            },
        ),
        migrations.CreateModel(
            name='Violations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='№ п.п.')),
                ('date_incedent', models.DateField(verbose_name='Дата проишествия')),
                ('author', models.CharField(max_length=100, verbose_name='ФИО автора')),
                ('change_date', models.DateField(auto_now_add=True, verbose_name='Дата изменения')),
                ('division', models.CharField(max_length=100, verbose_name='Дивизион')),
                ('filial', models.CharField(max_length=200, verbose_name='Филиал')),
                ('representation', models.CharField(verbose_name='Представительство')),
                ('entity', models.CharField(verbose_name='Юридическое лицо')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('type', models.CharField(max_length=100, verbose_name='Вид события')),
                ('way', models.CharField(max_length=40, verbose_name='Способ проникновения')),
                ('instrument', models.CharField(max_length=100, verbose_name='Средство совершения')),
                ('relation', models.CharField(max_length=100, verbose_name='В отношении')),
                ('object', models.CharField(max_length=150, verbose_name='Предмет посягательства')),
                ('place', models.CharField(max_length=300, verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Проишествие',
                'verbose_name_plural': 'Проишествия',
            },
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_intruder', models.BooleanField(verbose_name='Нарушитель')),
                ('is_witness', models.BooleanField(verbose_name='Свидетель')),
                ('is_injured', models.BooleanField(verbose_name='Потерпевший')),
                ('id_person', models.IntegerField(verbose_name='ID лица')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.violations', verbose_name='Номер события')),
            ],
        ),
    ]
