# Generated by Django 4.2 on 2023-04-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intruder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intruder_fio', models.CharField(max_length=100, verbose_name='ФИО нарушителя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('description', models.TextField(default='Нет описание (Нежелательное поведение)', verbose_name='Описание нарушителя')),
                ('sex', models.CharField(blank=True, max_length=1, verbose_name='Пол (м/ж)')),
                ('birthday', models.DateField(null=True, verbose_name='День рождения')),
                ('with_companion', models.CharField(blank=True, verbose_name='В компании с:')),
                ('adress_type', models.CharField(blank=True, verbose_name='Тип адреса')),
                ('country', models.CharField(blank=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, verbose_name='Область')),
                ('area', models.CharField(blank=True, verbose_name='Район')),
                ('locality', models.CharField(blank=True, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, verbose_name='Дом')),
                ('frame', models.CharField(blank=True, verbose_name='Корпус')),
                ('apartment', models.CharField(blank=True, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Нарушитель',
                'verbose_name_plural': 'Нарушители',
            },
        ),
        migrations.CreateModel(
            name='Violations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_incedent', models.DateField(verbose_name='Дата проишествия')),
                ('type', models.CharField(max_length=100, verbose_name='Тип проишествия')),
                ('author', models.CharField(max_length=100, verbose_name='ФИО автора')),
                ('change_date', models.DateField(auto_now_add=True)),
                ('division', models.CharField(max_length=100, verbose_name='Дивизион')),
                ('filial', models.CharField(max_length=200, verbose_name='Филиал')),
                ('representation', models.CharField(verbose_name='Представительство')),
                ('entity', models.CharField(verbose_name='Юридическое лицо')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('way', models.CharField(max_length=40, verbose_name='Тип события')),
                ('instrument', models.CharField(max_length=100, verbose_name='Средство совершения')),
                ('relation', models.CharField(max_length=100, verbose_name='Способ проникновения')),
                ('object', models.CharField(max_length=150, verbose_name='Предмет посягательства')),
                ('place', models.CharField(max_length=300, verbose_name='Место')),
                ('intruder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.intruder', verbose_name='ФИО нарушителя')),
            ],
            options={
                'verbose_name': 'Проишествие',
                'verbose_name_plural': 'Проишествия',
            },
        ),
    ]
