# Generated by Django 4.2 on 2023-05-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Дивизион', 'verbose_name_plural': 'БИБИЛИОТЕКА: Дивизионы'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Юридическое лицо', 'verbose_name_plural': 'БИБИЛИОТЕКА: Юридические лица'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'БИБИЛИОТЕКА: Филиалы'},
        ),
    ]
