# Generated by Django 4.2 on 2023-04-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedperson',
            name='id_event',
            field=models.IntegerField(verbose_name='Номер события'),
        ),
    ]
