# Generated by Django 4.2 on 2023-04-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_relatedperson_id_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedperson',
            options={'verbose_name': 'Связанное лицо', 'verbose_name_plural': 'Связанные лица'},
        ),
        migrations.AlterField(
            model_name='relatedperson',
            name='is_injured',
            field=models.BooleanField(default=False, verbose_name='Потерпевший'),
        ),
        migrations.AlterField(
            model_name='relatedperson',
            name='is_intruder',
            field=models.BooleanField(default=False, verbose_name='Нарушитель'),
        ),
        migrations.AlterField(
            model_name='relatedperson',
            name='is_witness',
            field=models.BooleanField(default=False, verbose_name='Свидетель'),
        ),
    ]
