# Generated by Django 4.2 on 2023-05-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_representation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='id_filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filial'),
        ),
    ]
