# Generated by Django 4.2 on 2023-04-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_violations_change_date_alter_violations_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injured',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID потерпевшего')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('who_is', models.CharField(max_length=200, verbose_name='Кем является:')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
            ],
            options={
                'verbose_name': 'Потерпевший',
                'verbose_name_plural': 'Потерпевшие',
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID свидетеля')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('who_is', models.CharField(max_length=200, verbose_name='Кем является:')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
            ],
            options={
                'verbose_name': 'Свидетель',
                'verbose_name_plural': 'Свидетели',
            },
        ),
        migrations.AddField(
            model_name='intruder',
            name='injureds',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Пострадавшие'),
        ),
        migrations.AddField(
            model_name='intruder',
            name='witnesses',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Пострадавшие'),
        ),
    ]
