# Generated by Django 4.2 on 2023-04-30 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_person_add_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='add_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 16, 8, 18, 533888), editable=False),
        ),
    ]
