# Generated by Django 4.2 on 2023-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_injured_witness_intruder_injureds_intruder_witnesses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intruder',
            name='injureds',
        ),
        migrations.RemoveField(
            model_name='intruder',
            name='witnesses',
        ),
        migrations.AddField(
            model_name='violations',
            name='injureds',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Пострадавшие'),
        ),
        migrations.AddField(
            model_name='violations',
            name='witnesses',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Пострадавшие'),
        ),
    ]
