# Generated by Django 4.2 on 2023-05-03 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_person_add_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='add_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 2, 32, 330954), editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('м', 'М'), ('ж', 'Ж')], verbose_name='Пол'),
        ),
    ]
