# Generated by Django 4.2 on 2023-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_intruder_injureds_remove_intruder_witnesses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violations',
            name='witnesses',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Свидетели'),
        ),
    ]
