# Generated by Django 4.2 on 2023-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_event_division_alter_event_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheradresses',
            name='description',
            field=models.CharField(blank=True, verbose_name='Описание адреса'),
        ),
    ]
