# Generated by Django 4.2 on 2023-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_violations_witnesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intruder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID нарушителя'),
        ),
    ]
